### ISSUE TITLE
众安面试

### ISSUE THREAD

**Issue by asevenm** [daodaoApp/interview#10]
1. 实现深拷贝
JSON.stringify有什么方法只转换部分属性（如：{a: 1, b: 2} -> '{"a": 1}')
2. 实现curry化
3. bind, call, apply区别
4. class constructor中调用super的作用
5. react做过什么优化
6. 高阶组件实现方式，它的作用是什么
7. 比较一下react-hooks版本和之前版本
8. 说说react-diff
9. 说说react-fiber
10. 设计组件你基于什么原则
11. https和http的区别，说说加密过程
12. 如何优化网站性能
13. 你webpack做过什么优化工作
splitChunks如何配置
如何优化构建速度
14. 实现布局：移动端垂直方向上，A,B两个div占满全屏，高度都自适应
15. 你是如何做前端项目（我现在的项目）的设计，在这个项目中有什么成长

**Comment by ChrisWen960216** [comment]
## 14. 实现布局：移动端垂直方向上，A,B两个div占满全屏，高度都自适应

```html
    <div className="App">
      <div className="top" />
      <div className="bottom" />
    </div>
```

```css
.App {
  display: flex;
  width: 100%;
  flex-direction: column;
  height: 100vh;
}

.top {
  border: 1px solid red;
  height: 100px;
}

.bottom {
  border: 1px solid green;
  flex: 1;
}

```

1. First set the parent box `height: 100vh`;
2. Then change one box's height and another box just set the `flex:1`, is that correct?
