### ISSUE TITLE
字节面试

### ISSUE THREAD

**Issue by asevenm** [daodaoApp/interview#4]
### 一轮：
1. 大整数加法
2. 实现一个类`Chain`

    ```js
    const chain = new Chain(); 
    chain.eat().sleep(5).work().sleep(6).eat();
    ```
3. 实现`bind`
4. 实现`JSON.stringify`
5. 讲一讲`webpack`的一些关键概念
6. 说说你对`typescript`的理解
7. 说说`redux`管理状态
8. `react` 生命周期

### 二轮：
1. 说说你项目中的比较有亮点的地方
2. 实现一个`strim`方法
3. 实现数组去重方法
4. `for`循环定义`setTimeout`输出问题，及解决方案
6. fn1 = x => x; fn2 = x => {x}; fn3 = x => ({ x }); fn1(2);fn2(2);fn3(3)输出什么？
7. 实现一个sum(1)(2, 3)(4)输出10；const result = sum(1)(2, 3)(4); console.log(result)输出10， result.value()输出10；
8. 类方法全局调用问题
9. `http`缓存;说说`http`有哪些版本
10. 长列表卡顿是因为什么？实现虚拟滚动
11. `css position`取值；如何脱离文档流；`transform`会脱离文档流吗？
12. 你了解哪些新的前端领域的技术；说说对微前端的理解
13. ` redux`工作流，`combineReducer`实现
14. 网络安全问题

### 一面：
1. `webpack`路由去中心化
*require.context*
2. 未知宽高实现垂直居中
```css
/*1*/
.wrap {
  display: flex;
  align-items: center;
  justify-content: center;
}
/*2*/
.content {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
/*3*/
.wrap {
  display: table;
  text-align: center;
}
.content {
  display: table-cell;
  vertical-align: middle;
}
```
3. 动画性能优化方案
*在使用css3 transtion做动画效果时，优先选择transform(opacity, rotate, scale, translate)，尽量不要使用height，width，margin和padding*
*创建单独的图层*

4. 基于`fetch`，封装一个带有超时和重试功能的请求

    ```js
    ajax({url, timeout, tryTimes})
    fetch(url).then
    ```
5.项目中比较有挑战性的地方
